#!/bin/sh
tmp=$(mktemp -d)

cd "$tmp" || exit 1
dd if=/dev/zero of=image seek=10G bs=1 count=0
mkfs.ext4 image
mkdir root
mount -o loop image root 
mkdir -p root/etc/xbps.d
cp /etc/xbps.d/* root/etc/xbps.d
mkdir -p root/var/cache/xbps
mount --bind -o ro /var/cache/xbps root/var/cache/xbps
xbps-install --repository='https://alpha.de.repo.voidlinux.org/current' --yes -U -S -r "$PWD/root" base-system ncurses-base
umount root/var/cache/xbps
chroot root xbps-reconfigure -a
for i in agetty-console dhcpcd; do
	ln -s "/etc/sv/$i" root/etc/runit/runsvdir/default/$i
done
echo "/bin/bash" | chroot root chsh root
for i in root/etc/sv/agetty-*; do
	echo "GETTY_ARGS='-a root'" > "$i/conf"
done

echo TERM=linux > root/etc/profile.d/term.sh
mkdir root/host
echo void /host 9p defaults 0 0 >> root/etc/fstab

cp "$(ls root/boot/vmlinuz-* | sort -V | tail -n 1)" vmlinuz
cp "$(ls root/boot/initramfs-* | sort -V | tail -n 1)" initrd
umount root

cat > run <<EOF
tmp="\$(dirname \$0)"
cd "\$tmp"
qemu-system-x86_64 \
	-kernel vmlinuz \
	-initrd initrd \
	-hda image \
	-enable-kvm \
	-append "root=/dev/sda console=ttyS0" \
	-m 1024 \
	-serial mon:stdio \
	-net user \
	-net nic \
	-virtfs local,id=void,path=/,security_model=mapped,readonly,mount_tag=void

echo "To start again execute \$tmp/run"
echo "Enter to delete the virtual machine, Ctrl-C to keep"
head -n 1
cd / || exit 1
rm -r "\$tmp"
EOF
chmod +x run
exec ./run
